import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {

  const [notices,setNotices] = useState([])
  const [search, setSearch] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)


useEffect(() =>{
// search the api 
async function fetchData(){
  setLoading(true)
  const data = await fetch(`https://ws-public.interpol.int/notices/v1/red?forename=${search}&resultPerPage=200`)
  .then((res) => res.json());
  setNotices(data._embedded.notices)
  setLoading(false)
}
fetchData()

},[search])



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input type="search" placeholder='search' onChange={(e)=>setSearch(e.target.value)}  />
        {JSON.stringify(notices)}
      </main>
    </div>
  )
}

export default Home
